app/urls.py
#Here are all of Pyum's URLS.
from django.conf.urls import patterns, url
from django.contrib import admin

from app import views


admin.autodiscover()

urlpatterns = patterns('',
                       #User types nothing, go to home
                       url(r'^$', views.home, name='home'),
                       #Register
                       url(r'^register/$', views.register, name='register'),
                       #Search Recipes
                       url(r'^search_recipes/$', views.search_recipes, name='search_recipes'),
                       #Log in
                       url(r'^login/$', views.user_login, name='login'),
                       #Log Out
                       url(r'^logout/$', views.user_logout, name='logout'),
                       #Home
                       url(r'^home/$', views.home, name='home'),
                       #Profile
                       url(r'^profile/$', views.profile, name='profile'),
                       #About
                       url(r'^about/$', views.about, name='about'),
                       #Static files, get django to serve em.
                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve'), )

pyum/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

#auto discover any admin urls
admin.autodiscover()

#This will basically direct any urls after the domain.
#App - into pyum
#Pyum - into pyum again
#admin - into the built-in admin site.
urlpatterns = patterns('',
                       url(r'^$', include('app.urls')),
                       url(r'^pyum/', include('app.urls')),
                       url(r'^app/', include('app.urls')),
                       url(r'^admin/', include(admin.site.urls)),
)

app/forms.py
#The forms are what we will be displaying to the user in the HTML
from django import forms
from django.contrib.auth.models import User

from app.models import AppUser


#User form, maps to user model
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


#User form number two, this is without a login field. Used on the profile page
class UserFormWithoutLogin(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password')


#App user form. Maps from App user model. Contains all of pyum specific data.
class AppUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AppUserForm, self).__init__(*args, **kwargs)
        self.fields['height'].label = "Height (inches)"
        self.fields['yummlydiet'].label = "Dietary Restriction"
        self.fields['goal'].label = "Goal (lbs per week)"

    class Meta:
        model = AppUser
        fields = ('yummlydiet', 'allergies', 'age', 'gender', 'height', 'diabetic', 'activity_level', 'goal')


#This is the form for recipe search. Does not directly tie to any model.
class RecipeSearchForm(forms.Form):
    ignore_user_preferences = forms.BooleanField()
    current_weight = forms.IntegerField()
    calories_consumed = forms.IntegerField()
    num_meals = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])
    in_ingredients = forms.CharField()
    ex_ingredients = forms.CharField()
    prep_time = forms.IntegerField()

app/templates/header.html
<html>
<head>z
    <style type="text/css">
        ul {
            margin-top: 10px;
            padding-top: 10px;
            list-style-type: none;
        }

        .top_banner{
            height: 100px;
        }

        h1.top_banner{
            color: white;
            font-weight: 400;
            font-family: Verdana, Geneva, sans-serif;
            margin: 0 auto;
            align: center;
        }

        li {
            display: inline;
        }
    </style>
    <link rel="stylesheet" href="{{ STATIC_URL }}app/css/screen.css"/>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href='{% static "app/css/templatemo_style.css" %}'>
</head>
<body>
<div id="templatemo_header" >
           <img src='{% static "app/img/pyum_round_w.png" %}' style = "float: left; width:100px; margin-left: 35px; margin-top:10px"/>
           <h1 class = "top_banner" style="margin: 30px; float: left;">Pyum</h1>
</div>
<div id="templatemo_main" >
    <div class="menu">
        <div id="templatemo_menu" style="display: inline; width: 100%">
            {% block templatemo_menu %}
                <div style="margin: 0; float: left; width: 200px; vertical-align: middle; padding: 0 6px 0 6px;">
                    <ul style="padding: 5px; margin: 0">
                        <li><a href="/app/home">Home</a></li>
                        <li><a href="/app/login">Login</a></li>
                        <li><a href="/app/register">Register</a></li>
                        <li><a href="/app/about">About</a></li>
                    </ul>
                </div>
                <div style="text-align: right; float: right; margin: 0; display: inline; vertical-align: middle; padding: 5px;">
                    <a href="/app/logout">Logout</a>
                </div>
            {% endblock %}
        </div>
    </div>
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>

</body>
</html>

app/templates/recipes.html
<!doctype html>
<html>

{% extends "header.html" %}
{% block title %}My amazing blog{% endblock %}
{% block content %}
{% load render_table from django_tables2 %}

<head>
    <title>Recipe Results</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}app/css/screen.css"/>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "app/css/templatemo_style.css" %}">
    <link rel="stylesheet" href='{% static "app/css/smoothness/jquery-ui-1.10.4.custom.min.css" %}'>
    <link rel="stylesheet" href='{% static "app/css/pyum.css" %}'>
</head>

<body>
<div id="templatemo_main" style="background-color: #771201; min-height: 330px">
    <div class="content_wrapper" style="background-color: #771201; min-width: 750px; border: none">
        <div style="margin-top: 10px">
        <div id="div_search" class="content_wrapper" style="background-color: #FFFFFF; width: 25%; min-width: 215px; float: left; border: 1px solid black; padding: 5px 10px 10px 10px">
            <input id="hide_search" type="button" value="Hide" onclick="changeSearchFormVisibility();" />
            <form id="form_search" action="/pyum/search_recipes/" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                <label for="id_ignore_user_preference">Ignore User Preferences:</label>
                {{ search_form.ignore_user_preferences }}

                <div id="divUserPreferences">
                    <label for="id_calories_consumed">Calories Consumed:</label>
                    {{ search_form.calories_consumed }}
                    <label for="id_current_weight">Current Weight (pounds):</label>
                    {{ search_form.current_weight}}
                    <label for="id_num_meals">Meals Left in the Day:</label>
                    {{ search_form.num_meals }}
                </div>

                <label for="id_in_ingredients">Included Ingredients:</label>
                {{ search_form.in_ingredients }}

                <label for="id_ex_ingredients">Excluded Ingredients:</label>
                {{ search_form.ex_ingredients }}

                <label for="id_prep_time">Preparation Time (in minutes):</label>
                {{ search_form.prep_time }}

                <div id="divSliders" style="text-align: left">
                    <div class="slider">
                        <p>
                            <label for="amount-sweetness">Sweetness:</label>
                            <input type="text" id="amount-sweetness" name="amount-sweetness" class="amount"
                                   style="border:0; color:#771201; font-weight:bold;">
                        </p>

                        <div id="range-sweetness" class="slider-range"></div>
                    </div>
                    <div class="slider">
                        <p>
                            <label for="amount-meatiness">Meatiness:</label>
                            <input type="text" id="amount-meatiness" name="amount-meatiness" class="amount"
                                   style="border:0; color:#771201; font-weight:bold;">
                        </p>
                        <div id="range-meatiness" class="slider-range"></div>
                    </div>
                    <div class="slider">
                        <p>
                            <label for="amount-sourness">Sourness:</label>
                            <input type="text" id="amount-sourness" name="amount-sourness" class="amount"
                                   style="border:0; color:#771201; font-weight:bold;">
                        </p>
                        <div id="range-sourness" class="slider-range"></div>
                    </div>
                    <div class="slider">
                        <p>
                            <label for="amount-sweetness">Bitterness:</label>
                            <input type="text" id="amount-bitterness" name="amount-bitterness" class="amount"
                                   style="border:0; color:#771201; font-weight:bold;">
                        </p>

                        <div id="range-bitterness" class="slider-range"></div>
                    </div>
                    <div class="slider">
                        <p>
                            <label for="amount-spicyness">Spicyness:</label>
                            <input type="text" id="amount-spicyness" name="amount-spicyness" class="amount"
                                   style="border:0; color:#771201; font-weight:bold;">
                        </p>

                        <div id="range-spicyness" class="slider-range"></div>
                    </div>
                </div>
                <input type="submit" value="Submit">
            </form>
        </div>
        <div style="width: 68%; float: left">
            <div id="table" style="float: left; min-width: 582px; width: 100%; background-color: #FFFFFF;">
            {% render_table table %}
            </div>
        </div>
        </div>
    </div>
</div>
<script type="text/javascript" src='{% static "app/js/jquery-1.3.2.min.js" %}'></script>
<script type='text/javascript' src='{% static "app/js/jquery-ui.min.js" %}'></script>
<script type='text/javascript' src='{% static "app/js/jquery.ui.core.min.js" %}'></script>
<script type='text/javascript' src='{% static "app/js/jquery.ui.widget.min.js" %}'></script>
<script type='text/javascript' src='{% static "app/js/jquery.ui.mouse.min.js" %}'></script>
<script type='text/javascript' src='{% static "app/js/jquery.ui.slider.min.js" %}'></script>
<script type='text/javascript' src='{% static "app/js/jquery.validate.js" %}' ></script>
<script type="text/javascript">
    $("#form_search").validate({
        rules: {
            current_weight: {
                number: true,
                required: true
            },
            calories_consumed: {
                number: true,
                required: true
            },
            prep_time: {
                number: true
            },
            in_ingredients:{
                required: true
            }
        }
    });

    function changeSearchFormVisibility(){
        var button = $("#hide_search");
        var div_search = $('#div_search');
        if(button.val() == "Hide"){
            $("#form_search").hide();
            button.val("Show");
            div_search.css('min-width', "55px");
            div_search.css('width', "55px");
        }
        else{
            $("#form_search").show();
            button.val("Hide");
            div_search.css('min-width', "215px");
            div_search.css('width', "25%");
        }

    }

    $("#id_ignore_user_preferences").change(function() {
        var div = $("#divUserPreferences");
        $("#id_current_weight").val("");
        $("#id_calories_consumed").val("");
        if($("#id_ignore_user_preferences").is(':checked')){
            div.hide();
        }else{
            div.show();
        }


    });

    $(".slider").each(function() {
        var $this = $(this);
        $( ".slider-range", $this).slider({
            range: true,
            min: 0,
            max: 10,
            step: 1,
            values: [ 0, 10 ],
            slide: function( event, ui ) {
                $( ".amount", $this ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] );
            }
        });
        $( ".amount", $this).val($( ".slider-range", $this ).slider( "values", 0 ) +
                " - " + $( ".slider-range", $this ).slider( "values", 1 ) );
    });

</script>

</body>
</html>
{% endblock %}